import { beforeEach, expect, it, vi } from 'vitest';
const m=vi.hoisted(()=>({calls:[] as string[],authValid:true,signOutStatus:0,storageFail:false,listed:false}));
vi.mock('../../../api/utils/rate-limit.js',()=>({checkRateLimit:()=>true}));
vi.mock('@supabase/supabase-js',()=>({createClient:()=>({auth:{getUser:async()=>({data:{user:m.authValid?{id:'synthetic-owner'}:null},error:null}),admin:{signOut:async()=>{m.calls.push('revoke');return {error:m.signOutStatus?{status:m.signOutStatus}:null};},deleteUser:async(id:string)=>{m.calls.push('identity:'+id);return {error:null};}}},rpc:async(name:string,args:any)=>{expect(args.p_user_id).toBe('synthetic-owner');m.calls.push(name);if(name==='delete_healthchain_user_data')return {error:null};const data=m.listed?[]:[{bucket_id:'health-records',name:'synthetic-original.pdf'}];m.listed=true;return {data,error:null};},storage:{from:(bucket:string)=>({remove:async(names:string[])=>{m.calls.push('bytes:'+bucket+':'+names.join(','));return {error:m.storageFail?new Error('temporary'):null};}})}})}));
beforeEach(()=>{vi.resetModules();vi.stubEnv('SUPABASE_URL','https://synthetic.supabase.co');vi.stubEnv('SUPABASE_SERVICE_ROLE_KEY','synthetic-not-a-secret');m.calls=[];m.authValid=true;m.signOutStatus=0;m.storageFail=false;m.listed=false;});
async function call(){const handler=(await import('../../../api/delete-account.js')).default;const result:any={code:0,body:null};const res:any={setHeader:()=>{},status:(code:number)=>{result.code=code;return res;},json:(body:any)=>{result.body=body;return res;}};await handler({method:'POST',headers:{authorization:'Bearer synthetic-token'}},res);return result;}
it('revokes sessions, deletes owned rows, erases actual file bytes and then removes identity',async()=>{expect(await call()).toMatchObject({code:200,body:{success:true}});expect(m.calls).toEqual(['revoke','delete_healthchain_user_data','list_healthchain_user_storage','bytes:health-records:synthetic-original.pdf','list_healthchain_user_storage','identity:synthetic-owner']);});
it('rejects expired authentication before destructive work',async()=>{m.authValid=false;expect((await call()).code).toBe(401);expect(m.calls).toEqual([]);});
it('does not claim deletion when session revocation fails',async()=>{m.signOutStatus=500;expect((await call()).code).toBe(503);expect(m.calls).toEqual(['revoke']);});
it('retries when an already revoked refresh session returns 404',async()=>{m.signOutStatus=404;expect(await call()).toMatchObject({code:200,body:{success:true}});});
it('retains an identity for retry and does not report success when file-byte removal fails',async()=>{m.storageFail=true;const result=await call();expect(result.code).toBe(500);expect(result.body.success).not.toBe(true);expect(m.calls.some(call=>call.startsWith('identity:'))).toBe(false);});
