import { beforeEach, expect, it, vi } from 'vitest';
const m = vi.hoisted(() => ({ user: 'push-owner' as string | null, device: true, configured: true, active: true, send: vi.fn(async () => ({ accepted: true, expired: false })), eq: vi.fn(), deleted: vi.fn() }));
vi.mock('@supabase/supabase-js', () => ({ createClient: () => ({ auth: { getUser: async () => ({ data: { user: m.user ? { id: m.user } : null }, error: null }) }, rpc: async () => ({ data: m.active, error: null }), from: () => {
  const q = { select: () => q, eq: (column: string, value: string) => { m.eq(column, value); return q; }, maybeSingle: async () => ({ data: m.device ? { platform: 'android' } : null, error: null }), delete: () => { m.deleted(); return q; }, then: (resolve: any) => resolve({ error: null }) }; return q;
} }) }));
vi.mock('../../../server/rate-limit.js', () => ({ checkRateLimit: () => true }));
vi.mock('../../../server/push-transport.js', () => ({ pushConfigured: () => m.configured, sendRemotePushTest: m.send }));
import handler from '../../../api/push-test.js';
beforeEach(() => { vi.stubEnv('SUPABASE_URL', 'https://synthetic.supabase.co'); vi.stubEnv('SUPABASE_ANON_KEY', 'synthetic-public-key'); m.user = 'push-owner'; m.device = m.configured = m.active = true; m.send.mockReset(); m.send.mockResolvedValue({ accepted: true, expired: false }); m.eq.mockClear(); m.deleted.mockClear(); });
async function call(extra: any = {}) { const result: any = {}; const res: any = { setHeader: () => {}, status: (code: number) => { result.code = code; return res; }, json: (body: any) => { result.body = body; return res; } }; await handler({ method: 'POST', headers: { authorization: 'Bearer synthetic' }, body: { token: 'synthetic-token', requestId: 'synthetic-request', userId: 'forged-owner' }, ...extra }, res); return result; }
it('only sends to the authenticated owners registered phone and reports acceptance without claiming delivery', async () => { expect(await call()).toMatchObject({ code: 202, body: { accepted: true, delivered: false } }); expect(m.eq).toHaveBeenCalledWith('user_id', 'push-owner'); expect(m.send).toHaveBeenCalledWith('android', 'synthetic-token', 'push-owner', 'synthetic-request'); });
it('rejects expired sign-in, erased accounts, foreign tokens and missing provider config', async () => { m.user = null; expect((await call()).code).toBe(401); m.user = 'push-owner'; m.active = false; expect((await call()).code).toBe(403); m.active = true; m.device = false; expect((await call()).code).toBe(409); m.device = true; m.configured = false; expect((await call()).body.error).toBe('remote_push_not_configured'); expect(m.send).not.toHaveBeenCalled(); });
it('removes only the expired installation token and surfaces provider rejection', async () => { m.send.mockResolvedValueOnce({ accepted: false, expired: true }); expect((await call()).code).toBe(409); expect(m.deleted).toHaveBeenCalledOnce(); expect(m.eq).toHaveBeenCalledWith('push_token', 'synthetic-token'); m.send.mockResolvedValueOnce({ accepted: false, expired: false }); expect((await call()).code).toBe(502); });
