import {
  Activity,
  AlertCircle,
  AlertTriangle,
  BatteryLow,
  Bone,
  Brain,
  BrainCircuit,
  CalendarClock,
  Droplets,
  Eye,
  Flame,
  Flower2,
  Focus,
  Heart,
  HeartPulse,
  Moon,
  ShieldAlert,
  Sparkles,
  Thermometer,
  Volume2,
  Waves,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export interface SymptomTheme {
  color1: string;
  color2: string;
  bgStart: string;
  bgEnd: string;
  border: string;
  activeBorder: string;
  activeBgStart: string;
  activeBgEnd: string;
  iconColor: string;
  textColor: string;
  shadow: string;
}

export const SYMPTOM_CATEGORY_THEMES: Record<string, SymptomTheme> = {
  gut: {
    color1: '#10B981',
    color2: '#D1FAE5',
    bgStart: '#ECFDF5',
    bgEnd: '#D1FAE5',
    border: '#A7F3D0',
    activeBorder: '#059669',
    activeBgStart: '#ECFDF5',
    activeBgEnd: '#D1FAE5',
    iconColor: '#059669',
    textColor: '#065F46',
    shadow: 'rgba(16, 185, 129, 0.25)',
  },
  neuro: {
    color1: '#8B5CF6',
    color2: '#EDE9FE',
    bgStart: '#F5F3FF',
    bgEnd: '#EDE9FE',
    border: '#DDD6FE',
    activeBorder: '#7C3AED',
    activeBgStart: '#F5F3FF',
    activeBgEnd: '#EDE9FE',
    iconColor: '#7C3AED',
    textColor: '#5B21B6',
    shadow: 'rgba(139, 92, 246, 0.25)',
  },
  respiratory: {
    color1: '#0284C7',
    color2: '#E0F2FE',
    bgStart: '#F0F9FF',
    bgEnd: '#E0F2FE',
    border: '#BAE6FD',
    activeBorder: '#0284C7',
    activeBgStart: '#F0F9FF',
    activeBgEnd: '#E0F2FE',
    iconColor: '#0284C7',
    textColor: '#0369A1',
    shadow: 'rgba(2, 132, 199, 0.25)',
  },
  cardio: {
    color1: '#FB7185',
    color2: '#FFE4E6',
    bgStart: '#FFF1F2',
    bgEnd: '#FFE4E6',
    border: '#FECDD3',
    activeBorder: '#E11D48',
    activeBgStart: '#FFF1F2',
    activeBgEnd: '#FFE4E6',
    iconColor: '#E11D48',
    textColor: '#9F1239',
    shadow: 'rgba(251, 113, 133, 0.25)',
  },
  pain: {
    color1: '#0D9488',
    color2: '#CCFBF1',
    bgStart: '#F0FDFA',
    bgEnd: '#CCFBF1',
    border: '#99F6E4',
    activeBorder: '#0D9488',
    activeBgStart: '#F0FDFA',
    activeBgEnd: '#CCFBF1',
    iconColor: '#0D9488',
    textColor: '#115E59',
    shadow: 'rgba(13, 148, 136, 0.25)',
  },
  skin: {
    color1: '#EC4899',
    color2: '#FCE7F3',
    bgStart: '#FDF2F8',
    bgEnd: '#FCE7F3',
    border: '#FBCFE8',
    activeBorder: '#DB2777',
    activeBgStart: '#FDF2F8',
    activeBgEnd: '#FCE7F3',
    iconColor: '#DB2777',
    textColor: '#9D174D',
    shadow: 'rgba(236, 72, 153, 0.25)',
  },
  systemic: {
    color1: '#F59E0B',
    color2: '#FEF3C7',
    bgStart: '#FFFBEB',
    bgEnd: '#FEF3C7',
    border: '#FDE68A',
    activeBorder: '#D97706',
    activeBgStart: '#FFFBEB',
    activeBgEnd: '#FEF3C7',
    iconColor: '#D97706',
    textColor: '#92400E',
    shadow: 'rgba(245, 158, 11, 0.25)',
  },
  sleep_mental: {
    color1: '#6366F1',
    color2: '#E0E7FF',
    bgStart: '#EEF2FF',
    bgEnd: '#E0E7FF',
    border: '#C7D2FE',
    activeBorder: '#4F46E5',
    activeBgStart: '#EEF2FF',
    activeBgEnd: '#E0E7FF',
    iconColor: '#4F46E5',
    textColor: '#3730A3',
    shadow: 'rgba(99, 102, 241, 0.25)',
  },
};

export interface SymptomItem {
  id: string;
  name: string;
  subtitle?: string;
  aliases?: string[];
  category:
    'gut' | 'neuro' | 'respiratory' | 'cardio' | 'pain' | 'skin' | 'systemic' | 'sleep_mental';
  icon: LucideIcon;
  isCommon?: boolean;
}

export const PRESET_SYMPTOMS: SymptomItem[] = [
  // --- MOST COMMON & HIGH-YIELD PRESENTING CONCERNS ---
  {
    id: 'fatigue',
    name: 'Fatigue',
    subtitle: 'Chronic Exhaustion & Low Energy',
    aliases: [
      'Fatigue / Chronic Exhaustion',
      'chronic exhaustion',
      'exhaustion',
      'tiredness',
      'low energy',
      'lethargy',
    ],
    category: 'systemic',
    icon: BatteryLow,
    isCommon: true,
  },
  {
    id: 'brain-fog',
    name: 'Brain Fog',
    subtitle: 'Cognitive Lag & Cloudy Focus',
    aliases: [
      'Brain Fog / Cognitive Lag',
      'cognitive lag',
      'cloudy thinking',
      'poor focus',
      'sluggish mind',
      'concentration',
    ],
    category: 'neuro',
    icon: Brain,
    isCommon: true,
  },
  {
    id: 'headache',
    name: 'Headache',
    subtitle: 'Migraine & Cranial Tension',
    aliases: [
      'Headache / Migraine',
      'migraine',
      'head tension',
      'cephalalgia',
      'temple throbbing',
      'cluster headache',
    ],
    category: 'neuro',
    icon: Zap,
    isCommon: true,
  },
  {
    id: 'bloating',
    name: 'Bloating',
    subtitle: 'Abdominal Gas & Distension',
    aliases: [
      'Abdominal Bloating & Gas',
      'bloating',
      'gas',
      'distension',
      'swollen stomach',
      'belly fullness',
    ],
    category: 'gut',
    icon: Waves,
    isCommon: true,
  },
  {
    id: 'acid-reflux',
    name: 'Acid Reflux',
    subtitle: 'Heartburn & Gastric Burning',
    aliases: [
      'Acid Reflux / Heartburn',
      'heartburn',
      'gerd',
      'indigestion',
      'burning chest',
      'sour taste',
    ],
    category: 'gut',
    icon: Flame,
    isCommon: true,
  },
  {
    id: 'abdominal-pain',
    name: 'Abdominal Pain',
    subtitle: 'Cramping & Visceral Spasms',
    aliases: [
      'Abdominal Cramping & Pain',
      'stomach cramps',
      'belly pain',
      'cramping',
      'gut ache',
      'stomach ache',
    ],
    category: 'gut',
    icon: AlertCircle,
    isCommon: true,
  },
  {
    id: 'joint-pain',
    name: 'Joint Pain',
    subtitle: 'Stiffness & Arthralgia',
    aliases: [
      'Joint Pain & Stiffness',
      'joint stiffness',
      'arthralgia',
      'stiff joints',
      'achy joints',
      'arthritis',
    ],
    category: 'pain',
    icon: Bone,
    isCommon: true,
  },
  {
    id: 'insomnia',
    name: 'Insomnia',
    subtitle: 'Sleep Disruption & Restless Nights',
    aliases: [
      'Insomnia / Sleep Disruption',
      'sleep disruption',
      'poor sleep',
      'cant sleep',
      'trouble sleeping',
      'sleeplessness',
    ],
    category: 'sleep_mental',
    icon: Moon,
    isCommon: true,
  },
  {
    id: 'anxiety',
    name: 'Anxiety',
    subtitle: 'Restlessness & High Tension',
    aliases: [
      'Anxiety & Restlessness',
      'restlessness',
      'nervousness',
      'worry',
      'panic',
      'apprehension',
    ],
    category: 'sleep_mental',
    icon: Heart,
    isCommon: true,
  },
  {
    id: 'shortness-of-breath',
    name: 'Shortness of Breath',
    subtitle: 'Air Hunger & Shallow Respiration',
    aliases: ['dyspnea', 'breathlessness', 'shallow breathing', 'air hunger', 'winded'],
    category: 'respiratory',
    icon: Wind,
    isCommon: true,
  },
  {
    id: 'chronic-cough',
    name: 'Chronic Cough',
    subtitle: 'Dry Cough & Throat Tickle',
    aliases: [
      'Chronic or Dry Cough',
      'dry cough',
      'persistent cough',
      'hacking cough',
      'throat tickle',
    ],
    category: 'respiratory',
    icon: Wind,
    isCommon: true,
  },
  {
    id: 'nausea',
    name: 'Nausea',
    subtitle: 'Queasiness & Gastric Unrest',
    aliases: ['Nausea & Queasiness', 'queasiness', 'upset stomach', 'sick to stomach', 'gagging'],
    category: 'gut',
    icon: AlertTriangle,
    isCommon: true,
  },
  {
    id: 'palpitations',
    name: 'Palpitations',
    subtitle: 'Heart Palpitations & Racing Pulse',
    aliases: [
      'Heart Palpitations & Racing',
      'heart palpitations',
      'palpitations',
      'racing heart',
      'fluttering',
      'pounding heart',
      'tachycardia',
    ],
    category: 'cardio',
    icon: HeartPulse,
    isCommon: true,
  },
  {
    id: 'low-back-pain',
    name: 'Low Back Pain',
    subtitle: 'Sciatica & Lumbar Stiffness',
    aliases: [
      'Low Back Pain / Sciatica',
      'sciatica',
      'lumbar pain',
      'back stiffness',
      'pinched nerve',
      'sacral pain',
    ],
    category: 'pain',
    icon: Bone,
    isCommon: true,
  },
  {
    id: 'skin-rash',
    name: 'Skin Rash',
    subtitle: 'Itching & Dermatitis Flare',
    aliases: ['Skin Rash & Itching', 'itching', 'hives', 'urticaria', 'dermatitis', 'red skin'],
    category: 'skin',
    icon: Flower2,
    isCommon: true,
  },

  // --- GASTROINTESTINAL & DIGESTION ---
  {
    id: 'constipation',
    name: 'Constipation',
    subtitle: 'Hard Stools & Straining',
    aliases: [
      'Constipation & Hard Stools',
      'hard stools',
      'irregular bowel',
      'straining',
      'infrequent stools',
    ],
    category: 'gut',
    icon: Activity,
  },
  {
    id: 'diarrhea',
    name: 'Diarrhea',
    subtitle: 'Loose & Watery Stools',
    aliases: [
      'Diarrhea / Loose Stools',
      'loose stools',
      'watery stools',
      'frequent bowel movements',
      'stomach bug',
    ],
    category: 'gut',
    icon: Droplets,
  },
  {
    id: 'belching',
    name: 'Belching',
    subtitle: 'Excessive Gas & Burping',
    aliases: ['Excessive Belching & Gas', 'burping', 'eructation', 'gas'],
    category: 'gut',
    icon: Wind,
  },
  {
    id: 'indigestion',
    name: 'Indigestion',
    subtitle: 'Dyspepsia & Upper Fullness',
    aliases: [
      'Indigestion / Dyspepsia',
      'dyspepsia',
      'sour stomach',
      'heavy digestion',
      'upper gut fullness',
    ],
    category: 'gut',
    icon: Flame,
  },
  {
    id: 'early-satiety',
    name: 'Early Satiety',
    subtitle: 'Quick Gastric Fullness',
    aliases: [
      'Early Satiety (Quick Fullness)',
      'quick fullness',
      'feeling full fast',
      'gastric fullness',
    ],
    category: 'gut',
    icon: Focus,
  },
  {
    id: 'loss-of-appetite',
    name: 'Loss of Appetite',
    subtitle: 'Food Aversion & Poor Hunger',
    aliases: ['anorexia', 'poor appetite', 'food aversion', 'not hungry'],
    category: 'gut',
    icon: Focus,
  },
  {
    id: 'food-intolerance',
    name: 'Food Sensitivity',
    subtitle: 'Histamine & Dietary Flare',
    aliases: [
      'Food Sensitivity Reaction',
      'food reaction',
      'food allergy',
      'histamine',
      'diet reaction',
    ],
    category: 'gut',
    icon: Flower2,
  },
  {
    id: 'difficulty-swallowing',
    name: 'Difficulty Swallowing',
    subtitle: 'Dysphagia & Throat Sensation',
    aliases: [
      'Difficulty Swallowing (Dysphagia)',
      'dysphagia',
      'throat lump',
      'food sticking',
      'globus',
    ],
    category: 'gut',
    icon: AlertCircle,
  },
  {
    id: 'ibs-flare',
    name: 'IBS / Bowel Spasms',
    subtitle: 'Spastic Colon & Gut Flares',
    aliases: [
      'Irritable Bowel Episodes (IBS)',
      'ibs',
      'irritable bowel',
      'gut flare',
      'spastic colon',
      'crampy gut',
    ],
    category: 'gut',
    icon: Activity,
  },
  {
    id: 'vomiting',
    name: 'Vomiting',
    subtitle: 'Emesis & Sudden Nausea Episodes',
    aliases: ['Vomiting Episodes', 'throwing up', 'emesis', 'dry heaving'],
    category: 'gut',
    icon: AlertTriangle,
  },

  // --- BRAIN & NEUROLOGICAL ---
  {
    id: 'dizziness-vertigo',
    name: 'Dizziness',
    subtitle: 'Vertigo & Room Spinning',
    aliases: [
      'Dizziness & Vertigo (Spinning)',
      'vertigo',
      'spinning',
      'unsteadiness',
      'room spinning',
      'loss of balance',
    ],
    category: 'neuro',
    icon: Focus,
  },
  {
    id: 'lightheadedness',
    name: 'Lightheadedness',
    subtitle: 'Presyncope & Faintness',
    aliases: [
      'Lightheadedness / Near-Fainting',
      'faintness',
      'presyncope',
      'near fainting',
      'wooziness',
    ],
    category: 'neuro',
    icon: Activity,
  },
  {
    id: 'tingling-numbness',
    name: 'Tingling / Numbness',
    subtitle: 'Neuropathy & Pins and Needles',
    aliases: [
      'Tingling / Numbness (Neuropathy)',
      'neuropathy',
      'pins and needles',
      'paresthesia',
      'numb hands',
      'numb feet',
    ],
    category: 'neuro',
    icon: Zap,
  },
  {
    id: 'tremors',
    name: 'Tremors / Twitching',
    subtitle: 'Involuntary Muscle Fasciculations',
    aliases: [
      'Tremors / Involuntary Twitching',
      'tremors',
      'shaking',
      'fasciculations',
      'involuntary twitch',
      'hand tremor',
    ],
    category: 'neuro',
    icon: Activity,
  },
  {
    id: 'tinnitus',
    name: 'Tinnitus',
    subtitle: 'Ear Ringing & Buzzing Sound',
    aliases: [
      'Tinnitus (Ear Ringing)',
      'ear ringing',
      'buzzing in ears',
      'ear whooshing',
      'pulsatile',
    ],
    category: 'neuro',
    icon: Volume2,
  },
  {
    id: 'photophobia',
    name: 'Light Sensitivity',
    subtitle: 'Photophobia & Sensory Overload',
    aliases: [
      'Light or Sound Sensitivity',
      'photophobia',
      'sound sensitivity',
      'hyperacusis',
      'sensory overload',
    ],
    category: 'neuro',
    icon: Eye,
  },
  {
    id: 'blurry-vision',
    name: 'Blurry Vision',
    subtitle: 'Diplopia & Eye Strain',
    aliases: [
      'Blurry or Fluctuating Vision',
      'vision fluctuation',
      'diplopia',
      'double vision',
      'eye strain',
    ],
    category: 'neuro',
    icon: Eye,
  },
  {
    id: 'memory-lapses',
    name: 'Memory Lapses',
    subtitle: 'Forgetfulness & Absentmindedness',
    aliases: [
      'Memory Lapses / Forgetfulness',
      'forgetfulness',
      'short term memory loss',
      'absentminded',
    ],
    category: 'neuro',
    icon: Brain,
  },
  {
    id: 'neck-stiffness',
    name: 'Neck Stiffness',
    subtitle: 'Cervical Tension & Limited Motion',
    aliases: [
      'Neck Stiffness & Tension',
      'cervical tension',
      'stiff neck',
      'restricted neck movement',
    ],
    category: 'neuro',
    icon: Focus,
  },

  // --- RESPIRATORY & ENT ---
  {
    id: 'sinus-pressure',
    name: 'Sinus Pressure',
    subtitle: 'Facial Congestion & Pain',
    aliases: [
      'Sinus Pressure & Facial Pain',
      'facial pain',
      'sinusitis',
      'forehead pressure',
      'sinus congestion',
    ],
    category: 'respiratory',
    icon: Wind,
  },
  {
    id: 'post-nasal-drip',
    name: 'Post-Nasal Drip',
    subtitle: 'Throat Clearing & Catarrh',
    aliases: ['mucus in throat', 'throat clearing', 'catarrh'],
    category: 'respiratory',
    icon: Wind,
  },
  {
    id: 'nasal-congestion',
    name: 'Nasal Congestion',
    subtitle: 'Stuffy Nose & Rhinitis',
    aliases: ['Nasal Congestion & Sneezing', 'stuffy nose', 'sneezing', 'blocked nose', 'rhinitis'],
    category: 'respiratory',
    icon: Wind,
  },
  {
    id: 'sore-throat',
    name: 'Sore Throat',
    subtitle: 'Pharyngitis & Scratchiness',
    aliases: ['Sore Throat & Scratchiness', 'pharyngitis', 'scratchy throat', 'throat irritation'],
    category: 'respiratory',
    icon: Flame,
  },
  {
    id: 'wheezing',
    name: 'Wheezing',
    subtitle: 'Bronchospasm & Asthmatic Rales',
    aliases: [
      'Wheezing / Asthmatic Rales',
      'asthma',
      'asthmatic rales',
      'bronchospasm',
      'noisy breathing',
    ],
    category: 'respiratory',
    icon: Wind,
  },
  {
    id: 'chest-tightness',
    name: 'Chest Tightness',
    subtitle: 'Bronchial & Airway Restriction',
    aliases: ['constricted chest', 'respiratory tightness', 'bronchial pressure'],
    category: 'respiratory',
    icon: Focus,
  },
  {
    id: 'productive-cough',
    name: 'Productive Cough',
    subtitle: 'Mucus & Phlegm Clearance',
    aliases: ['Productive Cough with Phlegm', 'cough with phlegm', 'mucus cough', 'sputum'],
    category: 'respiratory',
    icon: Droplets,
  },
  {
    id: 'loss-of-smell',
    name: 'Loss of Smell',
    subtitle: 'Anosmia & Ageusia (Taste Loss)',
    aliases: ['Loss of Smell or Taste', 'anosmia', 'loss of taste', 'ageusia', 'taste loss'],
    category: 'respiratory',
    icon: Focus,
  },
  {
    id: 'hoarseness',
    name: 'Hoarseness',
    subtitle: 'Voice Strain & Laryngitis',
    aliases: ['Hoarseness & Voice Strain', 'voice strain', 'raspy voice', 'laryngitis'],
    category: 'respiratory',
    icon: Wind,
  },

  // --- HEART & CIRCULATION ---
  {
    id: 'tachycardia',
    name: 'Rapid Pulse',
    subtitle: 'Resting Tachycardia & Bounding',
    aliases: ['Rapid Pulse (Tachycardia)', 'tachycardia', 'fast heart rate', 'bounding pulse'],
    category: 'cardio',
    icon: HeartPulse,
  },
  {
    id: 'chest-pressure',
    name: 'Chest Pressure',
    subtitle: 'Substernal Discomfort & Angina',
    aliases: [
      'Chest Pressure or Discomfort',
      'angina',
      'chest discomfort',
      'chest pain',
      'substernal pain',
    ],
    category: 'cardio',
    icon: ShieldAlert,
    isCommon: true,
  },
  {
    id: 'swollen-ankles',
    name: 'Swollen Ankles',
    subtitle: 'Peripheral Edema & Fluid Retention',
    aliases: [
      'Swollen Ankles or Legs (Edema)',
      'edema',
      'leg swelling',
      'fluid retention',
      'puffy ankles',
    ],
    category: 'cardio',
    icon: Droplets,
  },
  {
    id: 'cold-hands-feet',
    name: 'Cold Extremities',
    subtitle: 'Raynaud’s & Sluggish Circulation',
    aliases: [
      'Cold Hands & Feet (Poor Circulation)',
      'cold hands',
      'cold feet',
      'raynauds',
      'poor circulation',
    ],
    category: 'cardio',
    icon: Thermometer,
  },
  {
    id: 'orthostatic-dizzy',
    name: 'Postural Dizziness',
    subtitle: 'POTS & Standing Blood Drop',
    aliases: ['Dizziness When Standing Up', 'orthostatic hypotension', 'standing dizzy', 'pots'],
    category: 'cardio',
    icon: Activity,
  },

  // --- MUSCULOSKELETAL & PAIN ---
  {
    id: 'neck-shoulder-pain',
    name: 'Neck & Shoulder',
    subtitle: 'Trapezius Tension & Stiffness',
    aliases: [
      'Neck & Upper Shoulder Pain',
      'trapezius pain',
      'cervical pain',
      'shoulder stiffness',
    ],
    category: 'pain',
    icon: Bone,
  },
  {
    id: 'muscle-cramps',
    name: 'Muscle Cramps',
    subtitle: 'Nocturnal Spasms & Charley Horse',
    aliases: ['Muscle Cramps & Spasms', 'spasms', 'charley horse', 'calf cramps', 'twitching'],
    category: 'pain',
    icon: Zap,
  },
  {
    id: 'muscle-weakness',
    name: 'Muscle Weakness',
    subtitle: 'Loss of Strength & Heaviness',
    aliases: ['Muscle Weakness & Heaviness', 'heaviness', 'loss of strength', 'limb weakness'],
    category: 'pain',
    icon: Activity,
  },
  {
    id: 'morning-stiffness',
    name: 'Morning Stiffness',
    subtitle: 'Prolonged AM Joint Rigidity',
    aliases: [
      'Morning Stiffness (> 30 mins)',
      'early morning ache',
      'prolonged stiffness',
      'stiff joints AM',
    ],
    category: 'pain',
    icon: CalendarClock,
  },
  {
    id: 'joint-swelling',
    name: 'Joint Swelling',
    subtitle: 'Synovial Effusion & Warmth',
    aliases: ['Joint Swelling & Warmth', 'effusion', 'warm joints', 'puffy joints', 'synovitis'],
    category: 'pain',
    icon: Droplets,
  },
  {
    id: 'knee-pain',
    name: 'Knee Pain',
    subtitle: 'Patellar & Meniscal Ache',
    aliases: ['Knee Pain & Discomfort', 'patellar pain', 'meniscus', 'knee ache', 'runner knee'],
    category: 'pain',
    icon: Bone,
  },
  {
    id: 'body-aches',
    name: 'Body Aches',
    subtitle: 'Diffuse Myalgia & Flu-like Pain',
    aliases: [
      'Generalized Body Aches (Myalgia)',
      'myalgia',
      'generalized pain',
      'fibromyalgia aches',
      'flu-like aches',
    ],
    category: 'pain',
    icon: Activity,
  },

  // --- SKIN, HAIR & ALLERGIES ---
  {
    id: 'itching',
    name: 'Skin Itching',
    subtitle: 'Intense Pruritus & Scratching',
    aliases: ['Intense Skin Itching (Pruritus)', 'pruritus', 'severe itch', 'scratching'],
    category: 'skin',
    icon: Sparkles,
  },
  {
    id: 'eczema',
    name: 'Eczema',
    subtitle: 'Dry Flaking & Inflamed Patches',
    aliases: [
      'Eczema / Dry Inflamed Skin',
      'dermatitis',
      'dry inflamed skin',
      'flaking skin',
      'patchy skin',
    ],
    category: 'skin',
    icon: Droplets,
  },
  {
    id: 'acne-breakout',
    name: 'Acne',
    subtitle: 'Cystic Spots & Inflammatory Blemishes',
    aliases: ['Acne Breakouts & Cystic Spots', 'cystic acne', 'breakouts', 'pimples', 'blemishes'],
    category: 'skin',
    icon: Droplets,
  },
  {
    id: 'facial-flushing',
    name: 'Facial Flushing',
    subtitle: 'Rosacea & Sudden Burning Heat',
    aliases: ['Facial Flushing & Burning', 'rosacea', 'red face', 'burning face', 'hot flashes'],
    category: 'skin',
    icon: Flame,
  },
  {
    id: 'hair-loss',
    name: 'Hair Loss',
    subtitle: 'Alopecia & Telogen Shedding',
    aliases: [
      'Excessive Hair Shedding / Thinning',
      'alopecia',
      'hair thinning',
      'shedding hair',
      'telogen effluvium',
    ],
    category: 'skin',
    icon: Sparkles,
  },
  {
    id: 'easy-bruising',
    name: 'Easy Bruising',
    subtitle: 'Ecchymosis & Hematoma Susceptibility',
    aliases: ['Unexplained Easy Bruising', 'unexplained hematoma', 'ecchymosis', 'purpura'],
    category: 'skin',
    icon: AlertTriangle,
  },
  {
    id: 'angioedema',
    name: 'Facial Swelling',
    subtitle: 'Angioedema of Lips, Eyes, Face',
    aliases: [
      'Swollen Lips, Eyes, or Face',
      'swollen lips',
      'swollen eyes',
      'angioedema',
      'puffiness',
    ],
    category: 'skin',
    icon: ShieldAlert,
  },

  // --- SYSTEMIC, METABOLIC & IMMUNE ---
  {
    id: 'fever-chills',
    name: 'Fever / Chills',
    subtitle: 'Low-Grade Pyrexia & Shivering',
    aliases: [
      'Low-Grade Fever & Chills',
      'low-grade fever',
      'pyrexia',
      'shivering',
      'temperature spike',
    ],
    category: 'systemic',
    icon: Thermometer,
  },
  {
    id: 'night-sweats',
    name: 'Night Sweats',
    subtitle: 'Drenching Nocturnal Diaphoresis',
    aliases: [
      'Night Sweats / Drenching',
      'drenching sweats',
      'nocturnal diaphoresis',
      'waking up sweaty',
    ],
    category: 'systemic',
    icon: Droplets,
  },
  {
    id: 'unexplained-weight-loss',
    name: 'Weight Loss',
    subtitle: 'Rapid Involuntary Slimming',
    aliases: [
      'Unexplained Weight Loss',
      'unexplained weight loss',
      'rapid slimming',
      'dropping pounds',
    ],
    category: 'systemic',
    icon: Activity,
  },
  {
    id: 'unexplained-weight-gain',
    name: 'Weight Gain',
    subtitle: 'Fluid Retention & Rapid Shifts',
    aliases: ['Unexplained Rapid Weight Gain', 'rapid weight gain', 'water weight', 'sudden gain'],
    category: 'systemic',
    icon: Activity,
  },
  {
    id: 'swollen-lymph-nodes',
    name: 'Swollen Lymph Nodes',
    subtitle: 'Neck & Groin Lymphadenopathy',
    aliases: [
      'Swollen Lymph Nodes (Neck/Groin)',
      'lymphadenopathy',
      'neck lumps',
      'swollen glands',
      'groin nodes',
    ],
    category: 'systemic',
    icon: ShieldAlert,
  },
  {
    id: 'heat-cold-intolerance',
    name: 'Temp Intolerance',
    subtitle: 'Thyroid Chill & Heat Overload',
    aliases: ['Heat or Cold Intolerance', 'heat intolerance', 'cold intolerance', 'thyroid chill'],
    category: 'systemic',
    icon: Thermometer,
  },
  {
    id: 'excessive-thirst',
    name: 'Excessive Thirst',
    subtitle: 'Polydipsia & Persistent Dry Mouth',
    aliases: ['Excessive Thirst & Dry Mouth', 'polydipsia', 'dry mouth', 'constant thirst'],
    category: 'systemic',
    icon: Droplets,
  },

  // --- SLEEP & MENTAL WELLBEING ---
  {
    id: 'frequent-waking',
    name: 'Night Waking',
    subtitle: 'Broken Sleep & Nocturia',
    aliases: [
      'Frequent Nighttime Waking',
      'broken sleep',
      'waking up often',
      'fragmented sleep',
      'nocturia',
    ],
    category: 'sleep_mental',
    icon: Moon,
  },
  {
    id: 'daytime-sleepiness',
    name: 'Daytime Drowsiness',
    subtitle: 'Excessive Daytime Somnolence',
    aliases: [
      'Daytime Exhaustion & Drowsiness',
      'somnolence',
      'daytime fatigue',
      'dozing off',
      'sleepy during day',
    ],
    category: 'sleep_mental',
    icon: Moon,
  },
  {
    id: 'panic-episodes',
    name: 'Panic Episodes',
    subtitle: 'Acute Panic & Air Hunger Surges',
    aliases: [
      'Panic Attacks / Air Hunger',
      'panic attacks',
      'hyperventilation',
      'acute panic',
      'air hunger',
    ],
    category: 'sleep_mental',
    icon: HeartPulse,
  },
  {
    id: 'low-mood',
    name: 'Low Mood',
    subtitle: 'Depressed Affect & Low Motivation',
    aliases: ['Depressed Mood & Low Drive', 'depression', 'low drive', 'sadness', 'anhedonia'],
    category: 'sleep_mental',
    icon: Moon,
  },
  {
    id: 'chronic-stress',
    name: 'Chronic Stress',
    subtitle: 'Burnout & Nervous Overwhelm',
    aliases: ['Chronic Overwhelm & Stress', 'overwhelm', 'burnout', 'high tension', 'stress'],
    category: 'sleep_mental',
    icon: BrainCircuit,
  },
];

const presetByName = new Map<string, SymptomItem>();
const searchablePresets = PRESET_SYMPTOMS.map((symptom) => {
  const terms = [symptom.name, ...(symptom.aliases || [])].map((term) => term.toLowerCase());
  for (const term of terms) if (!presetByName.has(term)) presetByName.set(term, symptom);
  return { symptom, terms };
});

export function findPresetSymptom(name: string) {
  return presetByName.get(name.trim().toLowerCase());
}

export function filterPresetSymptoms(search: string, category: string): SymptomItem[] {
  const query = search.trim().toLowerCase();
  return searchablePresets
    .filter(({ symptom, terms }) =>
      query
        ? terms.some((term) => term.includes(query))
        : category === 'all' ||
          (category === 'common' ? symptom.isCommon : symptom.category === category)
    )
    .map(({ symptom }) => symptom);
}

export const STEP_META: Record<
  number,
  { title: string; subtitle: string; label: string; badge: string }
> = {
  1: {
    title: 'Which symptoms bother you?',
    subtitle:
      'Start with a few that matter most. You can search or pick from common clinical concerns below.',
    label: '1. Symptoms',
    badge: 'Symptom Cloud ✨',
  },
  2: {
    title: 'When did you first notice this?',
    subtitle: 'Knowing when this began helps distinguish acute episodes from chronic conditions.',
    label: '2. Timeline',
    badge: 'Onset Chronology ⏱️',
  },
  3: {
    title: 'How is the symptom behaving?',
    subtitle:
      'Trajectory helps clinicians evaluate urgency and inflammatory or mechanical patterns.',
    label: '3. Pattern',
    badge: 'Dynamics & Trend ↗️',
  },
  4: {
    title: 'Describe what you are experiencing',
    subtitle:
      'Your timeline narrative, symptom sensations, triggers, and questions in your own voice.',
    label: '4. Story',
    badge: 'Clinical Narrative 📝',
  },
  5: {
    title: 'Lab Reports & Medical Evidence',
    subtitle:
      'Attach relevant PDFs or images. They are sent to the review service when you run the review.',
    label: '5. Evidence',
    badge: 'Evidence Vault 📄',
  },
  6: {
    title: 'Review Scope & Launchpad',
    subtitle:
      'Confirm evidence readiness, set your clinical objective, and launch your clinical review.',
    label: '6. Launch',
    badge: 'Review & Run 🚀',
  },
};
