name: Lighthouse CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Install dependencies
        run: corepack enable pnpm && pnpm config set ignore-scripts true && pnpm install
        
      - name: Build project
        run: pnpm build

      - name: Run unit tests
        run: pnpm test run
        
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: './lighthouserc.cjs'
          uploadArtifacts: true
          temporaryPublicStorage: true
